services:
  backend:
    build:
      context: ./backend
      target: prod
    container_name: Backend_prod
    restart: unless-stopped
    env_file: ./backend/.env
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - upload_folder:/app/uploads
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - NODE_ENV=${NODE_ENV}
      - FRONTEND_URL=${FRONTEND_URL}
      - REDIS_URL=${REDIS_URL}

  frontend:
    build:
      context: ./frontend
      target: prod
    container_name: Frontend_prod
    restart: unless-stopped
    env_file: ./frontend/.env
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - API_URL=${API_URL}
      - NEXT_PUBLIC_API_PREFIX=${NEXT_PUBLIC_API_PREFIX}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}

volumes:
  postgres_data:
  upload_folder:
