services:
  postgres:
    image: postgres:17-alpine
    container_name: Database_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development_db_password
      POSTGRES_DB: my_portofolio_mikail
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      target: dev
    container_name: Backend_dev
    ports:
      - '8000:8000'
      - '4983:4983'
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
      - upload_folder_dev:/app/uploads
    env_file: ./backend/.env.development
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: Frontend_dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    env_file: ./frontend/.env.development

volumes:
  postgres_data_dev:
  upload_folder_dev:
